spring.application.name=gestao-iogurtes
server.port=8081
server.max-http-header-size=65536
security.jwt.secret=fc39dad9c68d206ab411f8c2f8776e951958f8f94e82117969aa80f3f3f6006924c3e52056b7336d201f388bc0c6525bb905d4551ef1264a

spring.datasource.url=jdbc:postgresql://localhost:5432/iogurtes_db
spring.datasource.username=postgres
spring.datasource.password=578999
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
